image: node:12

before_script:
  - npm install -g liyad-cli
  - npm ci

#cache:
#  paths:
#    - node_modules/

test:node:12:
  script:
    - liyad -p LSX_async --lsx-boot lsxboot.js index.lisp

test:node:11:
  image: node:11
  script:
    - liyad -p LSX_async --lsx-boot lsxboot.js index.lisp

# LTS
test:node:10:
  image: node:10
  script:
    - liyad -p LSX_async --lsx-boot lsxboot.js index.lisp
